
//! Autogenerated weights for `pallet_poe`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2024-02-03, STEPS: `20`, REPEAT: `10`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `DESKTOP-FPR505B`, CPU: `AMD Ryzen 7 4800U with Radeon Graphics`
//! WASM-EXECUTION: `Compiled`, CHAIN: `Some("dev")`, DB CACHE: `1024`

// Executed Command:
// ./target/debug/node-template
// benchmark
// pallet
// --chain
// dev
// --wasm-execution
// compiled
// --pallet
// pallet-poe
// --extrinsic
// *
// --steps
// 20
// --repeat
// 10
// --json-file=raw.json
// --output
// ./pallets/poe/src/weights.rs
// --template
// .maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_poe`.
pub trait WeightInfo {
	fn create_claim(d: u32, ) -> Weight;
	fn revoke_claim(d: u32, ) -> Weight;
	fn transfer_claim(d: u32, ) -> Weight;
}

/// Weights for `pallet_poe` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `Poe::Proofs` (r:1 w:1)
	/// Proof: `Poe::Proofs` (`max_values`: None, `max_size`: Some(118), added: 2593, mode: `MaxEncodedLen`)
	/// The range of component `d` is `[0, 64]`.
	fn create_claim(_d: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `3583`
		// Minimum execution time: 395_435_000 picoseconds.
		Weight::from_parts(611_898_884, 3583)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Poe::Proofs` (r:1 w:1)
	/// Proof: `Poe::Proofs` (`max_values`: None, `max_size`: Some(118), added: 2593, mode: `MaxEncodedLen`)
	/// The range of component `d` is `[0, 64]`.
	fn revoke_claim(d: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `84 + d * (1 ±0)`
		//  Estimated: `3583`
		// Minimum execution time: 465_860_000 picoseconds.
		Weight::from_parts(505_985_575, 3583)
			// Standard Error: 258_720
			.saturating_add(Weight::from_parts(1_459_742, 0).saturating_mul(d.into()))
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: `Poe::Proofs` (r:1 w:1)
	/// Proof: `Poe::Proofs` (`max_values`: None, `max_size`: Some(118), added: 2593, mode: `MaxEncodedLen`)
	/// The range of component `d` is `[0, 64]`.
	fn transfer_claim(_d: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `84 + d * (1 ±0)`
		//  Estimated: `3583`
		// Minimum execution time: 482_822_000 picoseconds.
		Weight::from_parts(606_041_439, 3583)
			.saturating_add(T::DbWeight::get().reads(1_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `Poe::Proofs` (r:1 w:1)
	/// Proof: `Poe::Proofs` (`max_values`: None, `max_size`: Some(118), added: 2593, mode: `MaxEncodedLen`)
	/// The range of component `d` is `[0, 64]`.
	fn create_claim(_d: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `6`
		//  Estimated: `3583`
		// Minimum execution time: 395_435_000 picoseconds.
		Weight::from_parts(611_898_884, 3583)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Poe::Proofs` (r:1 w:1)
	/// Proof: `Poe::Proofs` (`max_values`: None, `max_size`: Some(118), added: 2593, mode: `MaxEncodedLen`)
	/// The range of component `d` is `[0, 64]`.
	fn revoke_claim(d: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `84 + d * (1 ±0)`
		//  Estimated: `3583`
		// Minimum execution time: 465_860_000 picoseconds.
		Weight::from_parts(505_985_575, 3583)
			// Standard Error: 258_720
			.saturating_add(Weight::from_parts(1_459_742, 0).saturating_mul(d.into()))
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: `Poe::Proofs` (r:1 w:1)
	/// Proof: `Poe::Proofs` (`max_values`: None, `max_size`: Some(118), added: 2593, mode: `MaxEncodedLen`)
	/// The range of component `d` is `[0, 64]`.
	fn transfer_claim(_d: u32, ) -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `84 + d * (1 ±0)`
		//  Estimated: `3583`
		// Minimum execution time: 482_822_000 picoseconds.
		Weight::from_parts(606_041_439, 3583)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}